version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all_dependencies:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /locust/webui
    schedule:
      interval: monthly
    groups:
      eslint:
        patterns:
          - "*eslint*"
      vite:
        patterns:
          - "*vite*"
      react:
        patterns:
          - "*react*"
      emotion:
        patterns:
          - "*emotion*"
      mui:
        patterns:
          - "*mui*"
